### PR TITLE
fix: auto logout on api retry error

### LINKED ISSUE #11: Auto-Logout on API Retry Error
We are encountering an issue when making API calls after successfully refreshing the token. Upon completing the token refresh process, we proceeded to call the previous API again but encountered an unexpected error. The system redirected users back to the login page.

This issue is causing a disruption to the user experience and requires intervention to resolve.

### PR DESCRIPTION
**Pull request by letuankiet212**
Fix issue https://github.com/trandaison/nuxt-3-auth/issues/11

### CODE REVIEW

File: src/runtime/services/HttpService.ts [hunk 1]
```diff
@@ -57,8 +57,10 @@ export default class HttpService {
               Object.assign(context, ctx);
             },
           });
-        } catch {
-          await this.onAuthFailure(AuthStatus.Expired);
+        } catch (e) {
+          if ((e as (Partial<FetchError>)).status === HTTP_STATUS_UNAUTHORIZED) {
+            await this.onAuthFailure(AuthStatus.Expired);
+          }
```
Comment (trandaison) [inline src/runtime/services/HttpService.ts]: Please throw the error in the else case.

**Review by trandaison — APPROVED** [review]
LGTM!
